.changes/v1.0.0/4-features.md, .changes/v1.0.0/6-notes.md, vcfa/config.go, vcfa/config_test.go
Tests passed, logs contain only 40.0
=> Require API v40

.changes/v1.0.0/14-features.md, .github/workflows/check-code.yml, go.mod, go.sum, vcfa/config_test.go, vcfa/datasource_vcfa_org_oidc.go, vcfa/provider.go, vcfa/resource_vcfa_org_oidc.go, vcfa/resource_vcfa_org_oidc_test.go, vcfa/sample_vcfa_test_config.json, vcfa/structure.go, vcfa/vcfa_common_test.go, website/docs/d/org_oidc.html.markdown, website/docs/r/org_oidc.html.markdown, website/vcfa.erb
Add `vcfa_org_oidc` resource and data source.
To test it, a valid OIDC server is required:
```
"oidcServer": {
"url": "https://my-oidc-server:443/oidc",
"wellKnownEndpoint": "/.well-known/openid-configuration"
}
```
=> Add vcfa_org_oidc resource and data source

.changes/v1.0.0/15-features.md, go.mod, go.sum, vcfa/datasource_vcfa_org_networking.go, vcfa/provider.go, vcfa/resource_vcfa_org_networking.go, vcfa/resource_vcfa_org_networking_test.go, vcfa/structure.go, website/docs/d/org_networking.html.markdown, website/docs/r/org_networking.html.markdown, website/vcfa.erb
vcfa_org_networking resource + data source in Org Networking
Changes logname, that is a prerequisite for configuring Org Networking settings.
=> Add Org networking settings vcfa_org_networking resource + data source

.changes/v1.0.0/26-features.md, go.mod, go.sum, vcfa/datasource_vcfa_org_ldap.go, vcfa/provider.go, vcfa/resource_vcd_org_ldap_test.go, vcfa/resource_vcfa_org_ldap.go, website/docs/d/org_ldap.html.markdown, website/docs/r/org_ldap.html.markdown, website/vcfa.erb
This PR adds `vcfa_org_ldap` resource and data source.
To test it uses vCenter configured in the testing JSON configuration as LDAP server, so nothing special is needed.
=> Add vcfa_org_ldap resource and data source

.changes/v1.0.0/4-features.md, vcfa/resource_vcfa_nsx_manager_test.go
This PR removes reference to`network_provider_scope` field from TestAccVcfaNsxManager.
The field is no longer available.
Test passes
=> Remove network_provider_scope field from TestAccVcfaNsxManager

go.mod, go.sum
Bumps SDK which contains https://github.com/vmware/go-vcloud-director/pull/754, as it should not be needed anymore:
https://github.com/vmware/go-vcloud-director/releases/tag/v3.0.0-alpha.28
=> Bump SDK with Task workaround removal

.changes/v1.0.0/8-features.md, vcfa/resource_vcfa_ip_space_test.go, vcfa/vcfa_common_test.go
This PR creates unique IP Space scope names by hashing destination VCFA instance url and taking first 6 chars of it.
It may not be 100% unique, but should avoid problems with testing.
=> Use unique IP Space scopes in tests

.changes/v1.0.0/2-feature.md, vcfa/resource_generic_crud.go, vcfa/resource_vcfa_vcenter.go, vcfa/resource_vcfa_vcenter_test.go, vcfa/vcfa_common_test.go, website/docs/r/vcenter.html.markdown
Add options `refresh_vcenter_on_create`, `refresh_policies_on_create` to `vcfa_vcenter` in addition to already existing `refresh_policies_on_read` and `refresh_vcenter_on_read`.
Refreshing on every `read` operation (refresh, plan, apply) might be suboptimal due to time it might take sometimes, therefore `refresh_vcenter_on_create`, `refresh_policies_on_create` can be useful to ensure refresh is done once on creation to avoid Terraform failing on some missing storage policy.
=> vcfa_vcenter -  refresh_vcenter_on_create, refresh_policies_on_create

.changes/v1.0.0/12-features.md, go.mod, go.sum, vcfa/provider_test.go, vcfa/remove_leftovers_test.go, vcfa/resource_vcfa_content_library.go, vcfa/resource_vcfa_content_library_test.go, vcfa/resource_vcfa_org_region_quota_test.go, website/docs/d/content_library.html.markdown, website/docs/r/content_library.html.markdown
This PR adds a test for Tenant Content Libraries.
Tenant Content libraries need the `org_id` argument, when this is set, the Content Library will belong to an Organization.
The test creates a few libraries in a created Organization, and also logins as a tenant user to create a Content Library in this Organization.
The added test caught a bug in CL deletion (the error was being ignored). This PR also fixes that and updates documentation on this regard.
=> Test tenant Content Libraries

.changes/v1.0.0/12-features.md, go.mod, go.sum, vcfa/remove_leftovers_test.go
This PR:
* Bumps SDK
* Prevents Content Library cleanup for classic orgs
=> Tests: Do not cleanup classic org Content Libraries

.changes/v1.0.0/2-feature.md, vcfa/resource_vcfa_content_library_item_test.go, vcfa/resource_vcfa_content_library_test.go, vcfa/resource_vcfa_edge_cluster_qos_test.go, vcfa/resource_vcfa_ip_space_test.go, vcfa/resource_vcfa_org_region_quota_test.go, vcfa/resource_vcfa_org_regional_networking_test.go, vcfa/resource_vcfa_provider_gateway_test.go, vcfa/resource_vcfa_region_test.go, vcfa/resource_vcfa_vcenter.go, vcfa/resource_vcfa_vcenter_test.go, vcfa/vcfa_common_test.go, website/docs/r/vcenter.html.markdown
`vcfa_vcenter` adds a required field `nsx_manager_id` to enforce NSX Manager creation before vCenter creation.
=> vcfa_vcenter requires nsx_manager_id

.changes/v1.0.0/47-improvements.md, go.mod, go.sum, vcfa/resource_vcfa_vcenter.go, vcfa/sample_vcfa_test_config-cci.json, vcfa/sample_vcfa_test_config.json, website/docs/index.html.markdown
The `url` field in `provider` configuration does not require specifying API endpoint suffix `/tm/api` which is backed by https://github.com/vmware/go-vcloud-director/pull/765 change
Tests are passing.
=> provider.url should not require API path

go.mod, go.sum, vcfa/datasource_not_found_test.go, vcfa/resource_vcfa_vcenter.go
This PR patches broken TestAccDatasourceNotFound subtests and pulls in SDK from https://github.com/vmware/go-vcloud-director/pull/767
=> Patch TestAccDatasourceNotFound, bump SDK

.changes/v1.0.0/5-features.md, .changes/v1.0.0/8-features.md, go.mod, go.sum, vcfa/resource_vcfa_ip_space.go, vcfa/resource_vcfa_region.go
`vcfa_region` and `vcfa_ip_space`
=> Use async methods for IP Space and Region creation

.changes/v1.0.0/12-features.md, .changes/v1.0.0/13-features.md, vcfa/config.go, vcfa/resource_vcfa_content_library_item_test.go, vcfa/resource_vcfa_content_library_test.go
This PR fixes the test failure:
```
=== RUN   TestAccVcfaContentLibraryTenant
resource_vcfa_content_library_test.go:285: Step 4/6 error: Error running pre-apply refresh: exit status 1
Error: error getting Storage Class by Name 'vSAN Default Storage Policy': error retrieving all entities of type 'Storage Class': error getting all pages for endpoint https://my-vcfa.com/cloudapi/vcf/storageClasses/: error in HTTP GET request: NOT_AUTHENTICATED - [ 3258-2025-03-07-00-07-32-260--218b64dc-ad8d-43c6-9f9f-4c6eff270d9e ] This operation is denied.
with data.vcfa_storage_class.sc-tenant,
on terraform_plugin_test.tf line 167, in data "vcfa_storage_class" "sc-tenant":
167: data "vcfa_storage_class" "sc-tenant" {
--- FAIL: TestAccVcfaContentLibraryTenant (220.57s)
```
The issue happens because there is …
=> Fix NOT_AUTHENTICATED errors in Content Library tests

.changes/v1.0.0/52-notes.md, vcfa/config_test.go, vcfa/datasource_not_found_test.go, vcfa/datasource_vcfa_kubeconfig_test.go, vcfa/datasource_vcfa_right_test.go, vcfa/datasource_vcfa_tm_version_test.go, vcfa/resource_vcfa_api_token_test.go, vcfa/resource_vcfa_certificate_test.go, vcfa/resource_vcfa_content_library_item_test.go, vcfa/resource_vcfa_content_library_test.go, vcfa/resource_vcfa_edge_cluster_qos_test.go, vcfa/resource_vcfa_global_role_test.go, vcfa/resource_vcfa_ip_space_test.go, vcfa/resource_vcfa_nsx_manager_test.go, vcfa/resource_vcfa_org_ldap_test.go, vcfa/resource_vcfa_org_local_user_test.go, vcfa/resource_vcfa_org_networking_test.go, vcfa/resource_vcfa_org_oidc_test.go, vcfa/resource_vcfa_org_region_quota_test.go, vcfa/resource_vcfa_org_regional_networking_test.go, vcfa/resource_vcfa_org_test.go, vcfa/resource_vcfa_provider_gateway_test.go, vcfa/resource_vcfa_provider_ldap_test.go, vcfa/resource_vcfa_region_test.go, vcfa/resource_vcfa_rights_bundle_test.go, vcfa/resource_vcfa_role_test.go, vcfa/resource_vcfa_supervisor_namespace_test.go, vcfa/resource_vcfa_vcenter_test.go
This PR attempts to trigger immediate cleanup after any failed test so that the next tests do not conflict for left behind duplicate entries. 
Two things are done:
* `postTestChecks` is deferred immediately after `preTestChecks` instead of keeping it at the end. This way it will be triggered even if the tests fail
* `postTestChecks` will trigger leftover removal code in case the test is marked as failed and the leftover removal is not explicitly skipped`t.Failed() && !skipLeftoversRemoval`
Caveat - if the test panics - it won't help, but panic is a hard error anyway
Example recovery cleanup:
```
=== RUN   TestAccVcfaCertificateResource
resource_vcfa_certificate_test.go:69: Step 1/4 error: Error running apply: exit status 1
Error: [certificate library read] : error in HTTP GET request: …
```
=> Trigger cleanup after failed test to avoid resource clashes

.changes/v1.0.0/2-feature.md, .changes/v1.0.0/4-features.md, go.mod, go.sum
This PR just consumes https://github.com/vmware/go-vcloud-director/pull/771 that uses 15 as default pagesize for listing vCenters and NSX Managers
Tests `TestAccVcfaVcenter\b|TestAccVcfaNsxManager\b` passed, logs demonstrate pageSize of 15.
=> Bump SDK to use vCenter and NSX Manager pagination of 15

.changes/v1.0.0/26-features.md, vcfa/datasource_vcfa_org_ldap.go, vcfa/resource_vcfa_org_ldap.go, vcfa/resource_vcfa_org_ldap_test.go, vcfa/resource_vcfa_provider_ldap.go, vcfa/resource_vcfa_provider_ldap_test.go, website/docs/r/org_ldap.html.markdown, website/docs/r/provider_ldap.html.markdown
Before the changes implemented in this PR, users were forced to include a block in their `vcfa_provider_ldap` or `vcfa_org_ldap` definitions:
```
lifecycle {
ignore_changes = [password]
}
```
With these changes, this requirement is no more. The idea is to save the LDAP password as the user provides it on create/update, ignoring the backend in this case (which never returns it). On reads, we just recover the value from state.
If the password is changed, the mechanism works exactly the same, so it detects password changes as normal.
Acceptance tests:
```
go test -tags functional -run '^TestAcc.*Ldap' -v -timeout 0
```
Manual checks:
- Create `vcfa_provider_ldap` and `vcfa_org_ldap` HCL blocks. Apply as usual **without any `lifecycle` meta-argument**.
- Run `terraform plan`. No …
=> Improve LDAP password management

.changes/v1.0.0/13-features.md, vcfa/config_test.go, vcfa/provider_test.go, vcfa/resource_vcfa_content_library_test.go, vcfa/testcheck_funcs_test.go, vcfa/vcfa_common_test.go
This PR fixes a failing test introduced with PR 72, as the Content Library Item (Tenant test) is sharing same HCL as the Content Library. As I introduced vSphere provider, it fails. This PR isolates the vSphere snippet to be used only with Content Library test.
Also fixes some test tags, so one can do:
```
go test -tags contentlibrary -vcfa-skip-priority-tests -vcfa-add-provider -v -timeout 0
```
=> Amend PR 72

vcfa/config_test.go
The `getOrCreateNsxtManager` function was missing a check to fail gracefully if `GetNsxtManagerOpenApiByName` returned an error that is not ENF (Entity Not Found)
=> Fix getOrCreateNsxtManager function

.changes/v1.0.0/35-features.md, vcfa/resource_vcfa_supervisor_namespace_test.go
The test `TestAccVcfaSupervisorNamespace` was isolated and required special env variable to be set so that it is triggered.
This PR removes the skip option and runs the test by default.
=> Run namesapce test by default

.goreleaser.tmpl, .goreleaser.yml, terraform-registry-manifest.json
- Use GoReleaser configuration to v2 without deprecated items.
- Uses the recommended order.
- Add `.goreleaser.yml` for use by a release workflow.
- Add the `terraform-registry-manifest.json` needed for the release workflow. [Reference](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-release-publish#verify-terraform-registry-manifest-file).
Before:
```shell
terraform-provider-vcfa on main
➜ goreleaser check
• checking                                 path=.goreleaser.yml
• DEPRECATED:  archives.format  should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
• .goreleaser.yml                                  error=configuration is valid, but uses deprecated properties
⨯ command failed …
```
=> chore(gh): goreleaser v2

.github/workflows/release.yml
Adds the release workflow for the provider.
Will initialize the release workflow when tags for the following are pushed:
```yaml
- 'v*.*.*'    # Match stable releases. e.g. v1.2.3
- 'v*.*.*-*'  # Match pre-releases. e.g. v1.2.3-beta, v1.2.3-rc.1
```
=> chore(gh): add release workflow

go.mod, go.sum, vcfa/remove_leftovers_test.go
This PR bumps the SDK that contains this fix:
https://github.com/vmware/go-vcloud-director/pull/782
To get rid of the error:
```
Cannot invoke \"com.vmware.vcf.common.model.VirtualMachineClassInvModel.getDetails()\" because \"model\" is null",
"stackTrace": "java.lang.NullPointerException: Cannot invoke 
```
=> Fix NPE error when assigning VM Classes that don't specify their name

.changes/v1.0.0/35-features.md, vcfa/config_test.go, vcfa/resource_vcfa_supervisor_namespace_test.go
When the Supervisor Namespace is created too fast, it can happen that the Namespace Class is not found.
For 1.1 we may need to introduce retries, better than patching a test.
=> Fix Namespace Class not found

examples/greenfield/tenant/03-supervisor_namespaces.tf, vcfa/resource_vcfa_supervisor_namespace_test.go, vcfa/sample_vcfa_test_config-cci.json, vcfa/sample_vcfa_test_config.json
Rename the default VPC name to adhere to RFC1123 naming rules.
=> Rename default vpc name to adhere to naming rules
